"""Creation-only generator for provider-specific skill distributions."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

PROVIDERS = ("claude", "codex", "cursor", "gemini", "generic")
ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "skill" / "SKILL.src.md"
DIST = ROOT / "dist"
_VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")


def _exclusive(path: Path, content: str) -> None:
    path.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    try:
        with path.open("x", encoding="utf-8") as handle:
            handle.write(content)
    except FileExistsError:
        if path.read_text(encoding="utf-8") != content:
            raise RuntimeError(
                f"generated output differs and cannot be overwritten: {path}"
            ) from None


def _adapter(provider: str, source: str) -> str:
    banner = (
        f"<!-- Generated for {provider} from skill/SKILL.src.md. "
        "Do not edit this file manually. -->\n"
    )
    if provider == "claude":
        return banner + source
    lines = source.splitlines()
    filtered = [line for line in lines if not line.startswith("allowed-tools:")]
    note = (
        "\n> Runtime permission note: allow only the exact "
        "`python3 -m finance_skills <approved-subcommand>` commands listed below; "
        "never grant arbitrary Python or shell execution.\n"
    )
    insert_at = 4 if len(filtered) >= 4 else len(filtered)
    filtered.insert(insert_at, note)
    return banner + "\n".join(filtered) + "\n"


def generate() -> dict[str, object]:
    source = SOURCE.read_text(encoding="utf-8")
    skill_outputs: list[Path] = []
    for provider in PROVIDERS:
        path = DIST / provider / "SKILL.md"
        _exclusive(path, _adapter(provider, source))
        skill_outputs.append(path)

    checksums = []
    for path in skill_outputs:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        checksums.append(f"{digest}  {path.relative_to(DIST)}")
    checksum_path = DIST / "SHA256SUMS"
    _exclusive(checksum_path, "\n".join(checksums) + "\n")
    base_outputs = [*skill_outputs, checksum_path]

    sbom = {
        "spdxVersion": "SPDX-2.3",
        "name": "finance-skills-distributions",
        "files": [
            {
                "path": str(path.relative_to(ROOT)),
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            }
            for path in base_outputs
        ],
    }
    sbom_path = DIST / "sbom.json"
    _exclusive(sbom_path, json.dumps(sbom, indent=2, sort_keys=True) + "\n")
    base_outputs.append(sbom_path)

    support_sources = [
        *sorted((ROOT / "skill" / "reference").glob("*.md")),
        *sorted((ROOT / "skill" / "reference" / "shared").glob("*.md")),
        *sorted((ROOT / "skill" / "agents").glob("*.md")),
    ]
    support_outputs: list[Path] = []
    for provider in PROVIDERS:
        for support in support_sources:
            relative = support.relative_to(ROOT / "skill")
            target = DIST / provider / relative
            _exclusive(target, support.read_text(encoding="utf-8"))
            support_outputs.append(target)

    comprehensive = [*base_outputs, *support_outputs]
    checksums_v2 = [
        f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.relative_to(DIST)}"
        for path in comprehensive
    ]
    checksum_v2_path = DIST / "SHA256SUMS.v2"
    _exclusive(checksum_v2_path, "\n".join(checksums_v2) + "\n")
    comprehensive.append(checksum_v2_path)
    sbom_v2_path = DIST / "sbom.v2.json"
    sbom_v2 = {
        "spdxVersion": "SPDX-2.3",
        "name": "finance-skills-complete-distributions",
        "files": [
            {
                "path": str(path.relative_to(ROOT)),
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            }
            for path in comprehensive
        ],
    }
    _exclusive(sbom_v2_path, json.dumps(sbom_v2, indent=2, sort_keys=True) + "\n")
    comprehensive.append(sbom_v2_path)
    return {
        "status": "success",
        "outputs": [str(path) for path in comprehensive],
    }


def generate_versioned(version: str) -> dict[str, object]:
    """Create a complete immutable distribution beneath ``dist/<version>``."""
    if not _VERSION_RE.fullmatch(version):
        raise ValueError(f"invalid distribution version: {version!r}")
    output_root = DIST / version
    source = SOURCE.read_text(encoding="utf-8")
    outputs: list[Path] = []
    support_sources = [
        *sorted((ROOT / "skill" / "reference").glob("*.md")),
        *sorted((ROOT / "skill" / "reference" / "shared").glob("*.md")),
        *sorted((ROOT / "skill" / "agents").glob("*.md")),
    ]
    for provider in PROVIDERS:
        skill_path = output_root / provider / "SKILL.md"
        _exclusive(skill_path, _adapter(provider, source))
        outputs.append(skill_path)
        for support in support_sources:
            relative = support.relative_to(ROOT / "skill")
            target = output_root / provider / relative
            _exclusive(target, support.read_text(encoding="utf-8"))
            outputs.append(target)

    checksum_path = output_root / "SHA256SUMS"
    checksum_lines = [
        f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.relative_to(output_root)}"
        for path in outputs
    ]
    _exclusive(checksum_path, "\n".join(checksum_lines) + "\n")
    outputs.append(checksum_path)
    sbom_path = output_root / "sbom.json"
    sbom = {
        "spdxVersion": "SPDX-2.3",
        "name": f"finance-skills-distributions-{version}",
        "versionInfo": version,
        "files": [
            {
                "path": str(path.relative_to(ROOT)),
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            }
            for path in outputs
        ],
    }
    _exclusive(sbom_path, json.dumps(sbom, indent=2, sort_keys=True) + "\n")
    outputs.append(sbom_path)
    return {
        "status": "success",
        "version": version,
        "outputs": [str(path) for path in outputs],
    }


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if not args:
        result = generate()
    elif len(args) == 2 and args[0] == "--version":
        result = generate_versioned(args[1])
    else:
        raise SystemExit("usage: build_distributions.py [--version X.Y.Z]")
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
